apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-practice
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nagaraju7876482/nginx
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/reviewraj/gitops-practice.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
